version: '2.1'
services:
  rabbitmq:
    ports:
      - 5672:5672

  config:
    build: config
    ports:
      - 8888:8888

  registry:
    build: registry

  gateway:
    build: gateway

  auth-service:
    build: auth-service
    ports:
      - 5000:5000
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_DATA_MONGODB_URI: ${APPCONFIG_DOCUMENTDB_AUTH_URI}
      SPRING_DATA_MONGODB_SSL_ENABLED: "true"
      SPRING_DATA_MONGODB_SSL_INVALID_HOSTNAME_ALLOWED: "false"
      DOCUMENTDB_USERNAME: ${APPCONFIG_DOCUMENTDB_USERNAME}
      DOCUMENTDB_PASSWORD: ${APPCONFIG_DOCUMENTDB_PASSWORD}
      DOCUMENTDB_TLS_CA_FILE: ${APPCONFIG_DOCUMENTDB_TLS_CA_FILE}

  account-service:
    build: account-service
    ports:
      - 6000:6000
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_DATA_MONGODB_URI: ${APPCONFIG_DOCUMENTDB_ACCOUNT_URI}
      SPRING_DATA_MONGODB_SSL_ENABLED: "true"
      SPRING_DATA_MONGODB_SSL_INVALID_HOSTNAME_ALLOWED: "false"
      DOCUMENTDB_USERNAME: ${APPCONFIG_DOCUMENTDB_USERNAME}
      DOCUMENTDB_PASSWORD: ${APPCONFIG_DOCUMENTDB_PASSWORD}
      DOCUMENTDB_TLS_CA_FILE: ${APPCONFIG_DOCUMENTDB_TLS_CA_FILE}

  statistics-service:
    build: statistics-service
    ports:
      - 7000:7000
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_DATA_MONGODB_URI: ${APPCONFIG_DOCUMENTDB_STATISTICS_URI}
      SPRING_DATA_MONGODB_SSL_ENABLED: "true"
      SPRING_DATA_MONGODB_SSL_INVALID_HOSTNAME_ALLOWED: "false"
      DOCUMENTDB_USERNAME: ${APPCONFIG_DOCUMENTDB_USERNAME}
      DOCUMENTDB_PASSWORD: ${APPCONFIG_DOCUMENTDB_PASSWORD}
      DOCUMENTDB_TLS_CA_FILE: ${APPCONFIG_DOCUMENTDB_TLS_CA_FILE}

  notification-service:
    build: notification-service
    ports:
      - 8000:8000
    environment:
      SPRING_CLOUD_CONFIG_URI: http://config:8888
      SPRING_DATA_MONGODB_URI: ${APPCONFIG_DOCUMENTDB_NOTIFICATION_URI}
      SPRING_DATA_MONGODB_SSL_ENABLED: "true"
      SPRING_DATA_MONGODB_SSL_INVALID_HOSTNAME_ALLOWED: "false"
      DOCUMENTDB_USERNAME: ${APPCONFIG_DOCUMENTDB_USERNAME}
      DOCUMENTDB_PASSWORD: ${APPCONFIG_DOCUMENTDB_PASSWORD}
      DOCUMENTDB_TLS_CA_FILE: ${APPCONFIG_DOCUMENTDB_TLS_CA_FILE}

  monitoring:
    build: monitoring

  turbine-stream-service:
    build: turbine-stream-service