version: '2.1'
services:
  config:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
    image: sqshq/piggymetrics-config
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  gateway:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      AMAZON_MQ_BROKER_URL: ${AMAZON_MQ_BROKER_URL}
      DOCUMENTDB_URI: ${DOCUMENTDB_URI}
    image: sqshq/piggymetrics-gateway
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 80:4000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  auth-service:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      NOTIFICATION_SERVICE_PASSWORD: ${NOTIFICATION_SERVICE_PASSWORD}
      STATISTICS_SERVICE_PASSWORD: ${STATISTICS_SERVICE_PASSWORD}
      ACCOUNT_SERVICE_PASSWORD: ${ACCOUNT_SERVICE_PASSWORD}
      AMAZON_MQ_BROKER_URL: ${AMAZON_MQ_BROKER_URL}
      DOCUMENTDB_URI: ${DOCUMENTDB_URI}
    image: sqshq/piggymetrics-auth-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  account-service:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      ACCOUNT_SERVICE_PASSWORD: ${ACCOUNT_SERVICE_PASSWORD}
      AMAZON_MQ_BROKER_URL: ${AMAZON_MQ_BROKER_URL}
      DOCUMENTDB_URI: ${DOCUMENTDB_URI}
    image: sqshq/piggymetrics-account-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  statistics-service:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      STATISTICS_SERVICE_PASSWORD: ${STATISTICS_SERVICE_PASSWORD}
      AMAZON_MQ_BROKER_URL: ${AMAZON_MQ_BROKER_URL}
      DOCUMENTDB_URI: ${DOCUMENTDB_URI}
    image: sqshq/piggymetrics-statistics-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  notification-service:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      NOTIFICATION_SERVICE_PASSWORD: ${NOTIFICATION_SERVICE_PASSWORD}
      AMAZON_MQ_BROKER_URL: ${AMAZON_MQ_BROKER_URL}
      DOCUMENTDB_URI: ${DOCUMENTDB_URI}
    image: sqshq/piggymetrics-notification-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  monitoring:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      AMAZON_MQ_BROKER_URL: ${AMAZON_MQ_BROKER_URL}
      DOCUMENTDB_URI: ${DOCUMENTDB_URI}
    image: sqshq/piggymetrics-monitoring
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 9000:8080
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  turbine-stream-service:
    environment:
      SPRING_PROFILES_ACTIVE: cloud
      AWS_REGION: ${AWS_REGION}
      SECRETS_MANAGER_SECRET_NAME: ${SECRETS_MANAGER_SECRET_NAME}
      CONFIG_SERVICE_PASSWORD: ${CONFIG_SERVICE_PASSWORD}
      AMAZON_MQ_BROKER_URL: ${AMAZON_MQ_BROKER_URL}
      DOCUMENTDB_URI: ${DOCUMENTDB_URI}
    image: sqshq/piggymetrics-turbine-stream-service
    restart: always
    depends_on:
      config:
        condition: service_healthy
    ports:
      - 8989:8989
    logging:
      options:
        max-size: "10m"
        max-file: "10"