security:
  oauth2:
    client:
      clientId: account-service
      clientSecret: ${ACCOUNT_SERVICE_PASSWORD}
      accessTokenUri: ${AUTH_SERVICE_TOKEN_URI:http://localhost:5000/uaa/oauth/token}
      grant-type: client_credentials
      scope: server

spring:
  config:
    import: "optional:aws-secretsmanager:/piggymetrics/account-service"
  cloud:
    discovery:
      enabled: false
  data:
    mongodb:
      uri: ${ACCOUNT_DOCUMENTDB_URI:mongodb://${DOCDB_USERNAME:user}:${DOCDB_PASSWORD}@${DOCDB_HOST:localhost}:${DOCDB_PORT:27017}/${DOCDB_DATABASE:piggymetrics}?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false}
      database: ${DOCDB_DATABASE:piggymetrics}
      ssl:
        enabled: true

eureka:
  client:
    enabled: false

server:
  servlet:
    context-path: /accounts
  port: 6000

feign:
  hystrix:
    enabled: true