logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

service-discovery:
  cloud-map:
    registry-endpoint: ${SERVICE_REGISTRY_ENDPOINT:http://registry.internal:8761}
    auth-service-endpoint: ${AUTH_SERVICE_ENDPOINT:http://auth-service.internal:5000}

security:
  oauth2:
    resource:
      user-info-uri: ${AUTH_SERVICE_ENDPOINT:http://auth-service.internal:5000}/uaa/users/current

spring:
  rabbitmq:
    addresses: ${RABBITMQ_ENDPOINTS:amqps://b-1.example.mq.us-east-1.amazonaws.com:5671}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST:/}
    ssl:
      enabled: true
      algorithm: TLSv1.2