spring:
  config:
    import: aws-secretsmanager:/piggymetrics/auth-service
  cloud:
    discovery:
      enabled: false
  data:
    mongodb:
      uri: ${AUTH_MONGODB_URI:mongodb://${AUTH_MONGODB_USERNAME:user}:${AUTH_MONGODB_PASSWORD}@${AUTH_MONGODB_HOST:auth-docdb.cluster.local}:27017/piggymetrics?ssl=true&replicaSet=rs0&readPreference=secondaryPreferred&retryWrites=false}
      database: ${AUTH_MONGODB_DATABASE:piggymetrics}
      ssl:
        enabled: true

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

server:
  servlet:
    context-path: /uaa
  port: 5000