spring:
  data:
    mongodb:
      uri: ${DOCUMENTDB_MONGODB_URI}
      database: ${DOCUMENTDB_DATABASE:piggymetrics}
      ssl:
        enabled: ${DOCUMENTDB_TLS_ENABLED:true}
        invalid-hostname-allowed: ${DOCUMENTDB_TLS_INVALID_HOSTNAME_ALLOWED:false}

server:
  servlet:
    context-path: /uaa
  port: 5000