spring:
  data:
    mongodb:
      uri: ${appconfig.auth-service.documentdb.uri}
      username: ${appconfig.auth-service.documentdb.username}
      password: ${appconfig.auth-service.documentdb.password}
      database: ${appconfig.auth-service.documentdb.database:piggymetrics}
      ssl:
        enabled: true

server:
  servlet:
    context-path: /uaa
  port: 5000