hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

spring:
  cloud:
    aws:
      sqs:
        queue-url: ${SQS_QUEUE_URL}
      sns:
        topic-arn: ${SNS_TOPIC_ARN}

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    auth-service:
      path: /uaa/**
      url: ${AUTH_SERVICE_URL:http://auth-service.service.consul:5000}
      stripPrefix: false
      sensitiveHeaders:

    account-service:
      path: /accounts/**
      url: ${ACCOUNT_SERVICE_URL:http://account-service.service.consul:5000}
      stripPrefix: false
      sensitiveHeaders:

    statistics-service:
      path: /statistics/**
      url: ${STATISTICS_SERVICE_URL:http://statistics-service.service.consul:5000}
      stripPrefix: false
      sensitiveHeaders:

    notification-service:
      path: /notifications/**
      url: ${NOTIFICATION_SERVICE_URL:http://notification-service.service.consul:5000}
      stripPrefix: false
      sensitiveHeaders:

server:
  port: 4000