security:
  oauth2:
    client:
      clientId: statistics-service
      clientSecret: ${STATISTICS_SERVICE_PASSWORD}
      accessTokenUri: http://auth-service:5000/uaa/oauth/token
      grant-type: client_credentials
      scope: server

spring:
  data:
    mongodb:
      uri: ${APPCONFIG_DOCUMENTDB_URI}
      username: ${APPCONFIG_DOCUMENTDB_USERNAME}
      password: ${APPCONFIG_DOCUMENTDB_PASSWORD}
      database: ${APPCONFIG_DOCUMENTDB_DATABASE:piggymetrics}
      ssl:
        enabled: true

server:
  servlet:
    context-path: /statistics
  port: 7000

rates:
  url: https://api.exchangeratesapi.io